on:
  push:
    branches:
      - '*.*/stable'
  workflow_dispatch:
    branches:
      - '*.*/stable'

jobs:
  publish:
    name: Publish ROCK
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
